// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     user.avsc
 */
package generator

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionStringNullTypeEnum int
const (

	 UnionStringNullTypeEnumString UnionStringNullTypeEnum = 0

	 UnionStringNullTypeEnumNull UnionStringNullTypeEnum = 1

)

type UnionStringNull struct {

	String string

	Null *types.NullVal

	UnionType UnionStringNullTypeEnum
}

func writeUnionStringNull(r *UnionStringNull, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionStringNullTypeEnumString:
		return vm.WriteString(r.String, w)
        
	case UnionStringNullTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	}
	return fmt.Errorf("invalid value for *UnionStringNull")
}

func NewUnionStringNull() *UnionStringNull {
	return &UnionStringNull{}
}

func (_ *UnionStringNull) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionStringNull) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionStringNull) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionStringNull) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionStringNull) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionStringNull) SetString(v string) { panic("Unsupported operation") }
func (r *UnionStringNull) SetLong(v int64) { 
	r.UnionType = (UnionStringNullTypeEnum)(v)
}
func (r *UnionStringNull) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return (*types.String)(&r.String)
		
	
	case 1:
		
		
		return r.Null
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionStringNull) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionStringNull) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionStringNull) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionStringNull) Finalize()  { }
